71. Write a program that can perform union and intersection on 2 given list.

In [ ]:
list1 = list(input("Enter the elements"))
list2 = list(input("Enter the elements"))

def union_intersection(list1,list2):
  union = list1 + list2
  intersection = []
  for i in list1:
    if i in list2:
      intersection.append(i)
  print("unioin: ",union)
  print("intersection: ",intersection)

union_intersection(list1,list2)

Enter the elements12345
Enter the elements54678
unioin:  ['1', '2', '3', '4', '5', '5', '4', '6', '7', '8']
intersection:  ['4', '5']


72.the max item of each row of a matrix.

In [ ]:
a = [[1,2,3],
     [4,5,6],
     [7,8,9]]

def max_matrix(matrix):
  for i in matrix:
    print(max(i))

max_matrix(a)

3
6
9


73.Write a program that can convert an integer to string.

In [ ]:
a = int(input("Enter the number: "))
def convert_to_str(num):
  return str(num)

convert_to_str(a)

Enter the number: 123


'123'

74.Write a program to print the shape of a matrix.

In [ ]:
a = [[1,2,3,4],
     [4,5,6,7],
     [7,8,9,10]]

def shape_matrix(a):
  row = 0
  col = 0
  for i in a:
    row += 1
  for j in i:
    col += 1
  print("shape: ",(row,col))

shape_matrix(a)

shape:  (3, 4)


75.Write a program that can check if you can perform matrix
multiplication on 2 matrices

In [ ]:
import numpy as np
a = np.array([[1,2,3,4],
     [4,5,6,7],
     [7,8,9,10]])

b = np.array([[11,22,33,44],
     [44,55,66,77],
     [77,88,99,100]])

def multi_check(a,b):
  if a.shape == b.shape:
    print("the matrices can be multiplied.")
  else:
    print("the matrices cannot be multiplied.")

multi_check(a,b)   


the matrices can be multiplied.


76.Write a program to perform matrix multiplication on 2 matrices

In [ ]:
a = np.array([[1,2,3,4],
     [4,5,6,7],
     [7,8,9,10]])

b = np.array([[11,22,33,44],
     [44,55,66,77],
     [77,88,99,100]])

def mat_multi(a,b):
  if a.shape==b.shape:
    print(a*b)
  else:
    print("shape of the matrices don't match.")

mat_multi(a,b)

[[  11   44   99  176]
 [ 176  275  396  539]
 [ 539  704  891 1000]]


77. Write a program that can sort a given unsorted list. Dont use any built in
function for sorting.

In [ ]:
L = list(input("Enter the elements in the list: "))

def sort_list(L):
  sorted = []
  L1 = L
  for i in range(len(L1)):
    sorted.append(min(L1))
    L1.remove(min(L1))
  return sorted

sort_list(L)  

Enter the elements in the list: 54321


['1', '2', '3', '4', '5']

79.Assume a list with numbers from 1 to 10 and then convert it into a
dictionary where the key would be the numbers of the list and the
values would be the square of those numbers.

In [ ]:
L = [1,2,3,4,5,6,7,8,9,10]

dict1 = {i:i**2 for i in L} 
print(dict1)

{1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81, 10: 100}


80.Write a program to merge two given dictionary

In [ ]:
dict1 = {1:1,2:2,3:3,4:4}
dict2 = {5:5,6:6,7:7,8:8}

def merge(dict1,dict2):
  res = {**dict1,**dict2}
  return res

merge(dict1,dict2)

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}

In [ ]:
dict1 = {1:1,2:2,3:3,4:4}
dict2 = {5:5,6:6,7:7,8:8}

dict1.update(dict2)
dict1

{1: 1, 2: 2, 3: 3, 4: 4, 5: 5, 6: 6, 7: 7, 8: 8}